---
apiVersion: v1
kind: Namespace
metadata:
  name: prismarine-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: prismarine-client
---
apiVersion: v1
kind: Secret
metadata:
  name: prismarine-controller-secret
  namespace: prismarine-controller
type: Opaque
data:
  DATABASE_URL: <Password>
---
apiVersion: v1
kind: Pod
metadata:
  name: prismarine-controller
  labels:
    k8s.kashall.dev/controller: "true"
spec:
  containers:
  - name: prismarine-controller
    image: ghcr.io/kashalls/prismarine-k8s-master:main-59ee1368-1684265687
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000

