---
apiVersion: v1
kind: Namespace
metadata:
  name: prismarine-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: prismarine-client
---
apiVersion: v1
kind: Secret
metadata:
  name: prismarine-controller-secret
  namespace: prismarine-controller
type: Opaque
data:
  DATABASE_URL: <Password>
---
apiVersion: v1
kind: Pod
metadata:
  name: prismarine-controller
  namespace: prismarine-controller
  labels:
    k8s.kashall.dev/controller: "true"
spec:
  containers:
  - name: prismarine-controller
    image: ghcr.io/kashalls/prismarine-k8s-master:main-59ee1368-1684265687 # {"$imagepolicy": "flux-system:prismarine-controller"}
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: image-repo-policy
  namespace: flux-system
spec:
  podSelector: {}
  imageRepositoryRef:
    name: image-repo
  filterTags:
    pattern: '^.+-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: prismarine-client
spec:
  podSelector: {}
  egress:
    - to:
        - podSelector:
            matchLabels:
              - "k8s.kashall.dev/controller=true"
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - "10.0.0.0/8"
  ingress:
    - from:
        - podSelector: {}
        - ipBlock:
            cidr: "0.0.0.0/0"
  policyTypes:
    - Ingress
    - Egress
